In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [3]:
df = pd.read_csv(r"C:\Users\hi\Downloads\customer_support_tickets.csv\customer_support_tickets.csv")

print(df.head())

   Ticket ID        Customer Name              Customer Email  Customer Age  \
0          1        Marisa Obrien  carrollallison@example.com            32   
1          2         Jessica Rios    clarkeashley@example.com            42   
2          3  Christopher Robbins   gonzalestracy@example.com            48   
3          4     Christina Dillon    bradleyolson@example.org            27   
4          5    Alexander Carroll     bradleymark@example.com            67   

  Customer Gender Product Purchased Date of Purchase      Ticket Type  \
0           Other        GoPro Hero       2021-03-22  Technical issue   
1          Female       LG Smart TV       2021-05-22  Technical issue   
2           Other          Dell XPS       2020-07-14  Technical issue   
3          Female  Microsoft Office       2020-11-13  Billing inquiry   
4          Female  Autodesk AutoCAD       2020-02-04  Billing inquiry   

             Ticket Subject  \
0             Product setup   
1  Peripheral compatibil

In [13]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)
    return text

df['Ticket Description'] = df['Ticket Description'].apply(clean_text)

In [17]:
X = df['Ticket Description']
y = df['Ticket Type']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

category_model = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', LogisticRegression())
])

category_model.fit(X_train, y_train)

predictions = category_model.predict(X_test)

print(classification_report(y_test, predictions))

                      precision    recall  f1-score   support

     Billing inquiry       0.14      0.09      0.11       357
Cancellation request       0.19      0.22      0.21       327
     Product inquiry       0.20      0.19      0.20       316
      Refund request       0.18      0.22      0.20       345
     Technical issue       0.21      0.23      0.22       349

            accuracy                           0.19      1694
           macro avg       0.19      0.19      0.19      1694
        weighted avg       0.18      0.19      0.18      1694



In [21]:
X = df['Ticket Description']
y = df['Ticket Priority']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

priority_model = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', LogisticRegression())
])

priority_model.fit(X_train, y_train)

priority_predictions = priority_model.predict(X_test)

print(classification_report(y_test, priority_predictions))

              precision    recall  f1-score   support

    Critical       0.24      0.25      0.25       411
        High       0.26      0.29      0.27       409
         Low       0.24      0.23      0.24       415
      Medium       0.28      0.25      0.26       459

    accuracy                           0.26      1694
   macro avg       0.26      0.26      0.26      1694
weighted avg       0.26      0.26      0.26      1694



In [23]:
import joblib

joblib.dump(category_model, 'category_model.pkl')
joblib.dump(priority_model, 'priority_model.pkl')

['priority_model.pkl']

In [25]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, predictions)

print(cm)

[[  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [ 49  88   0   0   0   0  76  99  99]
 [ 62  90   0   0   0   0  75  98  84]
 [ 58  88   0   0   0   0  76 101  92]
 [ 57 109   0   0   0   0  76 109 108]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]]
